### ISSUE TITLE
[Suggestion] Meta-Data Improvements

### ISSUE THREAD

**Issue by Asinin3** [Difegue/LANraragi#116]
Important (to me):

- [ ] Add a way to fall-back to other plug-ins when running the Batch-Tagger, like how the auto-tagger works. e.g Run Eze plug-in but whenever it can't find a json file have it fall back to E-h and if that fails, fall back to chaika.
- [ ] Add a default timeout value specific to each scraper, most users wont have a clue what a value to use and risk getting themselves banned. Also grey-out the timeout value for eze plugin since it seems pointless to add a delay for it?

Less Important (to me):

- [ ] Exclude galleries in specific sub folders from automatic metadata fetching e.g a folder named "purged" could be ignored by specified plug-ins.
- [ ] Similar to the above suggestion, add a way to exclude (specified) sub folders from being (automatically) selected with the batch-tagger.
- [ ] Change the language used when searching for meta-data on sub folders with a specified name.

**Comment by softashell** [comment]
Plugin fallback would be great, I'm trying to migrate from old happypanda db I have but scraping tags is a pain with timeout since I have them already. Panda (rip) banning me after few hundred requests doesn't really help. Probably would be easier to just write a script to convert database directly.

Also having batch tagger skip things it has gotten proper tags for would be great. Currently it unticks even if getting tags failed.

**Comment by Difegue** [comment]
It'd indeed probably be easier to write a script/plugin that hooks into your own DB.  
I heard of the panda situation like two hours ago and probably won't have time to make anything for it.  

Unticking happens when the plugin returns a success iirc, but successes can be "i found no tags at all". Might be worth adding a third status type (error/success/neutral) here.

**Comment by Difegue** [comment]
Closing, see https://github.com/Difegue/LANraragi/issues/274#issuecomment-617350732 .
